### ISSUE TITLE
"Thread-0" class com.aspose.email.system.exceptions.NotImplementedException

### ISSUE THREAD

**Issue by tysongibby** [mkorthof/ost2pst#1]
Hi mkorthof,

Thanks for this sweet jar file. for some reason with I run it I get the following error and output.

OST2PST (180722)

INFO: Loading OST file G:\Mark\m******h.com.ost (417.1 MB)
INFO: Folder 0 Root - Public
INFO: Folder 1 Root - Mailbox
INFO: Converting G:\Mark\m******h.com.ost to G:\Mark\PST\liveviewtech.pst - 417087488 / 417112064 bytes
Exception in thread "Thread-0" class com.aspose.email.system.exceptions.NotImplementedException: The method or operation is not implemented
com.aspose.email.ake$b.a(SourceFile:3957)
com.aspose.email.ake.a(SourceFile:827)
com.aspose.email.ake.a(SourceFile:623)
com.aspose.email.wk.b(SourceFile:349)
com.aspose.email.acx.a(SourceFile:1754)
com.aspose.email.acx.b(SourceFile:732)
com.aspose.email.aox.a(SourceFile:893)
com.aspose.email.aox.b(SourceFile:1192)
com.aspose.email.PersonalStorage.convertTo(SourceFile:540)
com.aspose.email.PersonalStorage.saveAs(SourceFile:454)
com.ost2pst.LoadAndConvertOSTFileCLI$1.run(LoadAndConvertOSTFileCLI.java:66)
java.lang.Thread.run(Unknown Source)
        at com.aspose.email.ake$b.a(SourceFile:3957)
        at com.aspose.email.ake.a(SourceFile:827)
        at com.aspose.email.ake.a(SourceFile:623)
        at com.aspose.email.wk.b(SourceFile:349)
        at com.aspose.email.acx.a(SourceFile:1754)
        at com.aspose.email.acx.b(SourceFile:732)
        at com.aspose.email.aox.a(SourceFile:893)
        at com.aspose.email.aox.b(SourceFile:1192)
        at com.aspose.email.PersonalStorage.convertTo(SourceFile:540)
        at com.aspose.email.PersonalStorage.saveAs(SourceFile:454)
        at com.ost2pst.LoadAndConvertOSTFileCLI$1.run(LoadAndConvertOSTFileCLI.java:66)
        at java.lang.Thread.run(Unknown Source)

**Comment by tysongibby** [comment]
I forgot to mention the result is a corrupted pst file that cannot be opened by Outlook.

**Comment by mkorthof** [comment]
Hi

> I forgot to mention the result is a corrupted pst file that cannot be opened by Outlook.

Well, i guess that might be the problem then eh ;)
The lib ost2pst uses only converts, the PST must be readable.

I believe MS has a tool called "scanpst" that might be able to repair your PST.

**Comment by tysongibby** [comment]
Thanks, I'll see if that works.

**Comment by tysongibby** [comment]
Unfortunately, using the scanpst.exe to repair the file does not make the file readable by Outlook.

**Comment by tysongibby** [comment]
I think this error is causing the conversion to fail "Exception in thread "Thread-0" class com.aspose.email.system.exceptions.NotImplementedException: The method or operation is not implemented"

**Comment by mkorthof** [comment]
Basicly the stack trace tells you the lib cant handle some part at the end of your input OST file. It does not contain functionality to do repair.

Did you run scanpst on input OST? Then run ost2pst (if it was repaired).

**Comment by tysongibby** [comment]
Hi Marius. Thanks again for your response. Yes I did do the scanpst.exe to repair it. I have 5 different ost files. I have dried all the above process with them all and, unfortunately, I am having the same problem with all of them. This is why I was thinking it was more likely the error being thrown by the program.

**Comment by mkorthof** [comment]
Its also possible your OST version simply isnt supported by the lib: 

“Outlook 2013/2016 OST files are not supported”

Also, as the exception (com.apose.email.*) is clearly from the lib theres not much I can do without makes changes to it or switching to diff lib, which is not going to happen.

**Comment by tysongibby** [comment]
Thanks, Marius.

You are probably right, it is a newer file so it is probably just not compatible.

Hank
