### ISSUE TITLE
Java errors when running ost2pst

### ISSUE THREAD

**Issue by danzirulez** [mkorthof/ost2pst#11]
**Describe the bug**
Running either from the batch file or via the jar file the errors shown are java related. The file IS indeed a 2013 OST, as I understood though the output will NOT be a 2013 / 2016 pst which should be ok?

**Additional context**
java version 1.8.0_311-b11
![Screenshot 2022-01-18 at 12 25 39](https://user-images.githubusercontent.com/43517510/149928942-277edced-8938-4ec6-ad11-44d813b590ab.png)
![Screenshot 2022-01-18 at 12 25 52](https://user-images.githubusercontent.com/43517510/149928943-578c1470-1d38-4e52-81d2-527517725ccc.png)

**Comment by mkorthof** [comment]
Outlook 2013 is not supported.
Not sure why you got that stack trace, looks like the lib cannot even read your input file at all.
Normally some info about file format and folders is displayed and then it exits (it wont convert).
