### ISSUE TITLE
feature request: Support for Outlook 2013/2016 files

### ISSUE THREAD

**Issue by nconder** [mkorthof/ost2pst#7]
.\ost2pst.bat myost.ost Ost2Pst.pst

OST2PST (200316)

INFO: Loading OST file "myost.ost" (5GB)
      Folder [00] "Root - Public"
      Folder [01] "Root - Mailbox"

INFO: File format is "64-bit Unicode 4k, Outlook 2013" (36)
INFO: Saving Outlook 2013/2016 files is not supported, exiting...

**Comment by nconder** [comment]
found the other closed request that the api is not supporting this.

**Comment by jigar1859** [comment]
Saving Outlook 2013/2016 files is not supported, exiting.

**Comment by mkorthof** [comment]
Do NOT create issues about **saving to Outlook 2013/2016 PST files, they are _not supported_** and cannot be converted.
For details refer to README (and issues [#1](https://github.com/mkorthof/ost2pst/issues/1) [#2](https://github.com/mkorthof/ost2pst/issues/2) [#3](https://github.com/mkorthof/ost2pst/issues/3) [#4](https://github.com/mkorthof/ost2pst/issues/4))
